name: CI

on:
  push:
    branches:
      - 'main'
    tags:
      - v*
  pull_request:
    branches:
      - 'main'
      - 'develop'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '16.x', '18.x', '19.x' ]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Node ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: "${{ matrix.node }}"
      - run: npm install --save-dev hardhat
      - name: Create local node and deploy
        run: |
          npx hardhat node &
          npx hardhat run scripts/deploy.ts --network localhost
      - name: Run Tests
        run: REPORT_GAS=true npx hardhat test
      - name: Run Coverage
        run: |
          npx hardhat coverage &
          npx istanbul check-coverage --statements 90 --branches 90 --functions 90 --lines 90
